laszip 3.4.3 update
AnacondaRecipes/laszip-feedstock pull request #1
Opened 2023-09-27 20:20 UTC by Arishamays1

2023-09-27 20:21 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:38: invalid_url: https://www.laszip.org : HTTPSConnectionPool(host='www.laszip.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffb1991290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
ERROR: clone/recipe/meta.yaml:45: invalid_url: https://www.laszip.org/ : HTTPSConnectionPool(host='www.laszip.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffb199a650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Errors were found

</details>

2023-09-27 20:26 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:36: invalid_url: https://www.laszip.org : HTTPSConnectionPool(host='www.laszip.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff7a5a15d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
ERROR: clone/recipe/meta.yaml:43: invalid_url: https://www.laszip.org/ : HTTPSConnectionPool(host='www.laszip.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff7a5a2110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Errors were found

</details>

2023-09-28 14:22 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:36: invalid_url: https://www.laszip.org : HTTPSConnectionPool(host='www.laszip.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffb2156b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
ERROR: clone/recipe/meta.yaml:43: invalid_url: https://www.laszip.org/ : HTTPSConnectionPool(host='www.laszip.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffaf7a1210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Errors were found

</details>

2023-09-28 16:29 UTC, JeanChristopheMorinPerso requested changes

2023-09-28 16:29 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - pip
```suggestion
```
LASzip is a C++ package and doesn't contain any python related code.

2023-09-28 16:29 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +  skip: True  # [py<38]
```suggestion
```
This can be removed since Python isn't involved.

2023-09-28 18:01 UTC, cbouss approved these changes

2023-09-28 19:10 UTC, M-Waszkiewicz-Anaconda approved these changes
LGTM

2023-09-29 16:50 UTC, JeanChristopheMorinPerso approved these changes

2023-09-29 18:57 UTC, merged